@echo off
rem @@PROJECT_NAME@@ - test: script self-check on every page, then export both themes to out\.
rem Generated by `lui init`. ASCII-only on purpose (see run-dev.cmd for why).
rem
rem Step 1  `check .`  : assembles every page under src\ and collects script errors
rem                     (compile / runtime / unhandled rejection / I-O). Any error
rem                     means exit code 1, so this doubles as a CI gate.
rem Step 2  render      : both themes -> out\<page>-light.png and out\<page>-dark.png.
setlocal
set RUNTIME=@@RUNTIME@@

echo [1/2] self-check (any script error fails the build)
"%RUNTIME%" check . -w @@WIDTH@@ -H @@HEIGHT@@
if errorlevel 1 (
  echo [FAILED] self-check did not pass - see the diagnostics above
  exit /b 1
)

echo [2/2] export both themes -^> out\
"%RUNTIME%" render src\main.xml -O out -t both -w @@WIDTH@@ -H @@HEIGHT@@ --json
if errorlevel 1 exit /b 1

echo [DONE] tests passed
endlocal
