@echo off
rem @@PROJECT_NAME@@ - test: script self-check on every page, then export both themes to out\.
rem Generated by lui-render --init. ASCII-only on purpose (see run-dev.cmd for why).
rem
rem Step 1  --check  : offscreen render + collect script errors (compile / runtime /
rem                    unhandled rejection / I-O). Any error => exit code 1, so this is CI-ready.
rem Step 2  both themes -> out\<page>-light.png and out\<page>-dark.png, with a JSON summary.
setlocal
set RENDERER=@@RENDERER@@
set FAILED=0

echo [1/2] self-check (--check; any script error fails the build)
for %%F in (src\*.xml) do (
  echo   %%F
  "%RENDERER%" "%%F" --check -w @@WIDTH@@ -H @@HEIGHT@@
  if errorlevel 1 set FAILED=1
)
if "%FAILED%"=="1" (
  echo [FAILED] self-check did not pass - see the diagnostics above
  exit /b 1
)

echo [2/2] export both themes -^> out\
"%RENDERER%" src\main.xml -O out -t both -w @@WIDTH@@ -H @@HEIGHT@@ --json
if errorlevel 1 exit /b 1

echo [DONE] tests passed
endlocal
