@echo off
rem @@PROJECT_NAME@@ - development: window preview with hot reload.
rem   F5 = reload / T = switch theme / Esc = quit.
rem   Edits to xml / css / ts (including their dependencies) reload automatically.
rem Generated by `lui init`. If you move the runtime, edit the RUNTIME line below.
rem (ASCII-only on purpose: cmd.exe decodes .cmd files with the OEM code page, so
rem  non-ASCII text here would garble and can even be mis-parsed as commands.)
setlocal
set RUNTIME=@@RUNTIME@@

rem `dev .` reads lui.json from this folder: entry page, window size and theme
rem all come from the manifest, so there are no paths to keep in sync here.
"%RUNTIME%" dev . %*
if errorlevel 1 (
  echo.
  echo [ERROR] preview failed to start. Check the runtime path: %RUNTIME%
  exit /b 1
)
endlocal
