@echo off
rem @@PROJECT_NAME@@ - build: one self-contained executable.
rem   dist\@@PROJECT_NAME@@.exe contains the runtime, your pages and the ui/ component
rem   library. Copy it anywhere (no Pascal, no dependencies) and double-click to run.
rem Generated by `lui init`. ASCII-only on purpose (see run-dev.cmd for why).
setlocal
set RUNTIME=@@RUNTIME@@

"%RUNTIME%" build . %*
if errorlevel 1 exit /b 1

echo.
echo [DONE] dist\@@PROJECT_NAME@@.exe
echo   run it                 dist\@@PROJECT_NAME@@.exe
echo   export a screenshot    dist\@@PROJECT_NAME@@.exe -o out.png -t light
echo   script self-check      dist\@@PROJECT_NAME@@.exe --check
echo   list bundled files     dist\@@PROJECT_NAME@@.exe --list-bundle
endlocal
