@echo off
rem @@PROJECT_NAME@@ - package: build the app plus previews and a README.
rem   dist\ ends up holding the self-contained exe, preview-*.png and README.txt,
rem   so the whole folder can be zipped and handed over as-is.
rem Generated by `lui init`. ASCII-only on purpose (see run-dev.cmd for why).
setlocal
set RUNTIME=@@RUNTIME@@

"%RUNTIME%" pack . -t @@THEME@@ %*
if errorlevel 1 exit /b 1

echo.
echo [DONE] delivery folder: dist\
echo   contents: @@PROJECT_NAME@@.exe + preview-*.png + README.txt
endlocal
