@echo off
rem @@PROJECT_NAME@@ - development: launch the GUI preview.
rem   F5 = reload / T = switch theme / Esc = quit
rem Generated by lui-render --init. If you move the renderer, edit the RENDERER line below.
rem (This file is ASCII-only on purpose: cmd.exe decodes .cmd files with the OEM code page,
rem  so non-ASCII text here would garble and can even be mis-parsed as commands.)
setlocal
set RENDERER=@@RENDERER@@
set ENTRY=src\main.xml
set THEME=@@DEV_THEME@@

rem --watch also reloads on changes to dependencies (css / <include> / <script src>).
"%RENDERER%" "%ENTRY%" -t %THEME% --watch %*
if errorlevel 1 (
  echo.
  echo [ERROR] preview failed to start. Check the renderer path: %RENDERER%
  exit /b 1
)
endlocal
