@echo off
rem @@PROJECT_NAME@@ - package: assemble a shippable folder
rem   (renderer + ui/ runtime + pages + preview images + README.txt).
rem Generated by lui-render --init. ASCII-only on purpose (see run-dev.cmd for why).
rem
rem The whole dist\ folder can be copied to another machine and run as-is.
rem An existing non-empty target needs --force to be cleared and rebuilt.
setlocal
set RENDERER=@@RENDERER@@
set ENTRY=src\main.xml

"%RENDERER%" --pack dist "%ENTRY%" -t @@THEME@@ -w @@WIDTH@@ -H @@HEIGHT@@ --force
if errorlevel 1 exit /b 1

echo.
echo [DONE] delivery folder: dist\
echo   verify:  cd dist\pages ^&^& ..\lui-render.exe main.xml -o out.png
endlocal
